apiVersion: v1
kind: Service
metadata:
  name: openvpn
spec:
  type: LoadBalancer
  loadBalancerIP: 35.190.165.29
  selector:
    app: openvpn
  ports:
  - protocol: UDP
    port: 1194
    targetPort: 1194
